[[redirects]]
from="/*"
to="/index.html"
status=200
[build]
  command = "npm run build"
   commandOrigin= ui
   publish: /opt/build/repo/build
   publishOrigin: ui
   environment: - NODE_VERSION

[build.environment]
  NODE_VERSION = "18"